export const metadata = {
  title: "Arabic Stories",
  // description: "Generated by Next.js",
};

export default function ArabicStoriesLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
