export const metadata = {
  title: "Paintings By Story",
  // description: "Generated by Next.js",
};

export default function PaintingByStoryLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
