export const metadata = {
  title: "People",
  // description: "Generated by Next.js",
};

export default function PeopleLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
