export const metadata = {
  title: "ManuScripts",
  description: "Generated by Next.js",
};

export default function ManuScriptsLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
