import Footer from "../components/Footer";
import Header from "../components/Header";

export const metadata = {
  title: "Pemmtastic",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>

      <body>
        <main>
          <div className="relative">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
