export const metadata = {
  title: "Arabic Manuscripts",
  // description: "Generated by Next.js",
};

export default function ArabicManuscriptsLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
