export const metadata = {
  title: "Research And Lessons",
  // description: "Generated by Next.js",
};

export default function ResearchAndLessonsLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
