export const metadata = {
  title: "Using The Site",
  // description: "Generated by Next.js",
};

export default function UsingTheSiteLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
