export const metadata = {
  title: "Pemmtastic",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>

      <body>{children}</body>
    </html>
  );
}
