import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";

export const metadata = {
  title: "Maps",
  // description: "Generated by Next.js",
};

export default function MapsLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
