export const metadata = {
  title: "List of Repositories",
  // description: "Generated by Next.js",
};

export default function RepositoriesLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
