export const metadata = {
  title: "Paintings By Manuscript",
  // description: "Generated by Next.js",
};

export default function PaintingByManuscriptLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
