export const metadata = {
  title: "News And Updates",
  // description: "Generated by Next.js",
};

export default function NewsAndUpdatesLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
