export const metadata = {
  title: "Events And Workshops",
  // description: "Generated by Next.js",
};

export default function EventsAndWorkshopsLayout({ children }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}
